### ISSUE TITLE
libvlc_MetadataCancel_issue

### ISSUE THREAD

**Issue by ramayash** [lakhman/MobileVLCKit#1]
Please try to resolved the given following issue related with MobileVLCKit in xcode 9.2 , swift4.0 .
1.libvlc_MetadataCancel(creating player instance with private library as options were given)
2.playlist_preparser_Cancel
3.vlc_custom_create
4.reating player instance using shared library
Issue occur when try to play MobileVLCKit more than one time.

**Comment by lakhman** [comment]
You should view: https://wiki.videolan.org/VLCKit/

I haven't worked with VLC in years, Apologies but I'm going to have to close this.
